// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfHrzZ34pAhnykCN2YN8-8pOXufOHmLio',
    appId: '1:493360948592:web:c1cbc3a09d0611d39edbb5',
    messagingSenderId: '493360948592',
    projectId: 'gemini-3-hackathon-seoul',
    authDomain: 'gemini-3-hackathon-seoul.firebaseapp.com',
    storageBucket: 'gemini-3-hackathon-seoul.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKKiCupV_0DM_YN-AXpmNgcGQFz_BIFfM',
    appId: '1:493360948592:ios:7f85feaebeb8b27a9edbb5',
    messagingSenderId: '493360948592',
    projectId: 'gemini-3-hackathon-seoul',
    storageBucket: 'gemini-3-hackathon-seoul.firebasestorage.app',
    iosBundleId: 'com.creativedeliverables.geminiHackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfHrzZ34pAhnykCN2YN8-8pOXufOHmLio',
    appId: '1:493360948592:web:73a8ae0ea23b4d939edbb5',
    messagingSenderId: '493360948592',
    projectId: 'gemini-3-hackathon-seoul',
    authDomain: 'gemini-3-hackathon-seoul.firebaseapp.com',
    storageBucket: 'gemini-3-hackathon-seoul.firebasestorage.app',
  );
}
